name: abrar_shop
description: "Online Shopping App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  iconsax: ^0.0.8

  #firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3

  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

  image_picker: ^1.1.2

#------ dev ---------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/


  fonts:
    - family: Telenor
      fonts:
      - asset: assets/fonts/Telenor-Light.ttf
        weight: 300
      - asset: assets/fonts/Telenor-Medium.ttf
        weight: 500
      - asset: assets/fonts/Telenor-Bold.ttf
        weight: 800

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
