name: abrar_shop
description: "Online Shopping App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  iconsax: ^0.0.8

  #firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3

  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  path_provider: ^2.1.4
  image: ^4.2.0
#  tflite: ^1.1.2
  tflite_v2: ^1.0.0
  file_picker: ^8.0.7
  reorderables: ^0.6.0
  flutter_dropzone: ^4.0.2
#  tflite_flutter: ^0.10.4



#------ dev ---------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/


  fonts:
    - family: Telenor
      fonts:
      - asset: assets/fonts/Telenor-Light.ttf
        weight: 300
      - asset: assets/fonts/Telenor-Medium.ttf
        weight: 500
      - asset: assets/fonts/Telenor-Bold.ttf
        weight: 800
    - family: HindSiliguri
      fonts:
      - asset: assets/fonts/HindSiliguri-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
